/**
 * `codexa init` — Initialize project-specific CODEXA configuration
 *
 * Creates .codexa/ in the current project with:
 *   instructions.md   ← coding conventions, project rules
 *   architecture.md   ← auto-generated project architecture description
 *   config.json       ← project-level settings (overrides global)
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { detectProject } from "./project-detector.ts";

const c = {
  reset: "\x1b[0m",
  bold: "\x1b[1m",
  dim: "\x1b[2m",
  cyan: "\x1b[36m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
};

export async function runInitCommand(cwd: string = process.cwd()): Promise<void> {
  const codexaDir = join(cwd, ".codexa");

  if (existsSync(codexaDir)) {
    console.log(`\n${c.yellow}⚠ .codexa/ already exists in this project.${c.reset}`);
    console.log(`  Edit the files in ${codexaDir} to customize CODEXA's behavior.\n`);
    return;
  }

  console.log(`\n${c.cyan}${c.bold}Initializing CODEXA in this project...${c.reset}\n`);

  mkdirSync(codexaDir, { recursive: true });

  // Detect project for architecture description
  const info = detectProject(cwd);

  // ── instructions.md ───────────────────────────────────────────────────────
  const instructionsMd = `# CODEXA Project Instructions

These instructions guide CODEXA's behavior in this project.
Edit this file to customize how CODEXA works with your codebase.

## Coding Conventions

<!-- Add your project-specific conventions here. Examples: -->
- Follow the existing code style and naming conventions
- Always use TypeScript with strict mode
- Add JSDoc comments to all exported functions
<!-- - Do not introduce new dependencies without confirmation -->
<!-- - Run tests after any backend changes -->

## Architecture Notes

<!-- Describe your project architecture here so CODEXA understands the big picture -->
See architecture.md for the auto-detected project structure.

## Important Files

<!-- List key files CODEXA should always be aware of -->
${generateKeyFilesList(info)}

## Restrictions

<!-- List anything CODEXA should NOT do without explicit permission -->
- Always ask before committing to git
- Do not modify database migrations without confirmation
`;

  writeFileSync(join(codexaDir, "instructions.md"), instructionsMd, "utf-8");

  // ── architecture.md ───────────────────────────────────────────────────────
  const architectureMd = generateArchitectureMd(info, cwd);
  writeFileSync(join(codexaDir, "architecture.md"), architectureMd, "utf-8");

  // ── config.json ───────────────────────────────────────────────────────────
  const configJson = {
    version: 1,
    description: `CODEXA project configuration for ${info.name}`,
    routing: {
      enabled: false,
      planModel: null,
      buildModel: null,
    },
    context: {
      tokenBudget: 80000,
      excludeDirs: ["node_modules", ".git", "dist", "build", "coverage"],
    },
  };

  writeFileSync(
    join(codexaDir, "config.json"),
    JSON.stringify(configJson, null, 2),
    "utf-8",
  );

  // ── Output ─────────────────────────────────────────────────────────────
  console.log(`${c.green}✓ Created .codexa/instructions.md${c.reset}  ← Add your project rules here`);
  console.log(`${c.green}✓ Created .codexa/architecture.md${c.reset}  ← Auto-generated project overview`);
  console.log(`${c.green}✓ Created .codexa/config.json${c.reset}      ← Project-level CODEXA settings`);

  console.log(`\n${c.dim}Tip: Add .codexa/ to .gitignore if you don't want to share it,`);
  console.log(`or commit it to share CODEXA instructions with your team.${c.reset}\n`);
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function generateKeyFilesList(info: ReturnType<typeof detectProject>): string {
  const files: string[] = [];
  if (existsSync(join(info.path, "package.json"))) files.push("- package.json");
  if (existsSync(join(info.path, "tsconfig.json"))) files.push("- tsconfig.json");
  if (existsSync(join(info.path, "README.md"))) files.push("- README.md");
  if (existsSync(join(info.path, ".env.example"))) files.push("- .env.example");
  return files.join("\n") || "- (none detected)";
}

function generateArchitectureMd(
  info: ReturnType<typeof detectProject>,
  cwd: string,
): string {
  const lines: string[] = [
    `# ${info.name} — Architecture`,
    ``,
    `> Auto-generated by \`codexa init\`. Update this file to reflect your actual architecture.`,
    ``,
    `## Project Overview`,
    ``,
    `- **Name**: ${info.name}`,
    `- **Path**: ${cwd}`,
    `- **Languages**: ${info.languages.join(", ") || "unknown"}`,
    `- **Frameworks**: ${info.frameworks.join(", ") || "none detected"}`,
    `- **Package Manager**: ${info.packageManager}`,
    `- **Test Framework**: ${info.testFramework}`,
    `- **Git**: ${info.hasGit ? "Yes" : "No"}`,
    `- **Files tracked**: ${info.fileCount}`,
    ``,
    `## Directory Structure`,
    ``,
    `\`\`\``,
    generateDirTree(cwd),
    `\`\`\``,
    ``,
    `## Key Components`,
    ``,
    `<!-- Describe the main components of your application here -->`,
    `- (edit this section to describe your architecture)`,
  ];

  return lines.join("\n");
}

function generateDirTree(cwd: string, depth = 0, maxDepth = 2): string {
  if (depth > maxDepth) return "";
  const { readdirSync, statSync } = require("node:fs");
  const { join: pathJoin } = require("node:path");

  const SKIP = new Set(["node_modules", ".git", "dist", "build", ".next", "coverage", ".cache"]);
  const lines: string[] = [];

  try {
    const entries = readdirSync(cwd).filter((e: string) => !SKIP.has(e) && !e.startsWith(".") || e === ".codexa");
    for (const entry of entries.slice(0, 20)) {
      const full = pathJoin(cwd, entry);
      const indent = "  ".repeat(depth);
      try {
        const stat = statSync(full);
        if (stat.isDirectory()) {
          lines.push(`${indent}${entry}/`);
          if (depth < maxDepth) {
            lines.push(generateDirTree(full, depth + 1, maxDepth));
          }
        } else {
          lines.push(`${indent}${entry}`);
        }
      } catch {}
    }
  } catch {}

  return lines.filter(Boolean).join("\n");
}
