import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { CodexaLensActivityEvent } from "@codexa/shared";

export interface SessionExportData {
  sessionId: string;
  projectName?: string;
  timestamp: string;
  durationMs: number;
  totalTokens: number;
  estimatedCostUsd: number;
  events: CodexaLensActivityEvent[];
}

export function generateTimelineHtml(data: SessionExportData): string {
  const eventsHtml = data.events
    .map((e, index) => {
      const statusColor =
        e.status === "verified"
          ? "#10b981"
          : e.status === "failed"
            ? "#ef4444"
            : e.status === "modified"
              ? "#f59e0b"
              : "#3b82f6";
      const statusIcon =
        e.status === "verified"
          ? "✓ Verified"
          : e.status === "failed"
            ? "× Failed"
            : e.status === "modified"
              ? "◆ Modified"
              : "◉ Inspected";

      return `
      <tr>
        <td>#${index + 1}</td>
        <td><code>${e.toolName}</code></td>
        <td><span class="badge" style="background: ${statusColor}22; color: ${statusColor}; border: 1px solid ${statusColor};">${statusIcon}</span></td>
        <td>${e.summary || e.filePaths.join(", ") || "-"}</td>
        <td>+${(e.offsetMs / 1000).toFixed(1)}s</td>
        <td>${e.durationMs ? `${e.durationMs}ms` : "-"}</td>
      </tr>
      `;
    })
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CODEXA Timeline Report - ${data.sessionId}</title>
  <style>
    :root {
      --bg: #0d1117;
      --card-bg: #161b22;
      --border: #30363d;
      --text: #c9d1d9;
      --text-muted: #8b949e;
      --accent: #58a6ff;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: var(--bg);
      color: var(--text);
      margin: 0;
      padding: 32px;
      line-height: 1.5;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-bottom: 1px solid var(--border);
      padding-bottom: 16px;
      margin-bottom: 24px;
    }
    h1 { margin: 0; font-size: 24px; color: #fff; }
    .meta { color: var(--text-muted); font-size: 14px; }
    .metrics-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 16px;
      margin-bottom: 32px;
    }
    .card {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 16px;
    }
    .card .val { font-size: 22px; font-weight: bold; color: var(--accent); }
    .card .lbl { font-size: 12px; color: var(--text-muted); text-transform: uppercase; margin-top: 4px; }
    table {
      width: 100%;
      border-collapse: collapse;
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 8px;
      overflow: hidden;
    }
    th, td {
      padding: 12px 16px;
      text-align: left;
      border-bottom: 1px solid var(--border);
      font-size: 14px;
    }
    th { background: #21262d; color: var(--text-muted); font-weight: 600; }
    code { font-family: "SFMono-Regular", Consolas, monospace; font-size: 13px; background: #21262d; padding: 2px 6px; border-radius: 4px; }
    .badge { padding: 4px 8px; border-radius: 12px; font-size: 12px; font-weight: 600; display: inline-block; }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1>⚡ CODEXA Session Activity Report</h1>
      <div class="meta">Session ID: <code>${data.sessionId}</code> · Exported ${data.timestamp}</div>
    </div>
    <div class="meta">Generated by CODEXA CodexaLens</div>
  </div>

  <div class="metrics-grid">
    <div class="card">
      <div class="val">${(data.durationMs / 1000).toFixed(1)}s</div>
      <div class="lbl">Session Duration</div>
    </div>
    <div class="card">
      <div class="val">${data.events.length}</div>
      <div class="lbl">Total Tool Calls</div>
    </div>
    <div class="card">
      <div class="val">${data.totalTokens.toLocaleString()}</div>
      <div class="lbl">Total Tokens</div>
    </div>
    <div class="card">
      <div class="val">$${data.estimatedCostUsd.toFixed(4)}</div>
      <div class="lbl">Estimated Cost</div>
    </div>
  </div>

  <h2>Timeline Activity Replay</h2>
  <table>
    <thead>
      <tr>
        <th>Step</th>
        <th>Tool</th>
        <th>Status</th>
        <th>Summary</th>
        <th>Time Offset</th>
        <th>Execution Duration</th>
      </tr>
    </thead>
    <tbody>
      ${eventsHtml || '<tr><td colspan="6">No activity recorded in session timeline.</td></tr>'}
    </tbody>
  </table>
</body>
</html>`;
}

export async function exportSessionTimeline(
  sessionId: string = "active-session",
  outputPath: string = "codexa-timeline-export.html",
  events: CodexaLensActivityEvent[] = [],
): Promise<string> {
  const resolvedPath = resolve(process.cwd(), outputPath);
  const html = generateTimelineHtml({
    sessionId,
    timestamp: new Date().toISOString(),
    durationMs: events.reduce((max, e) => Math.max(max, e.offsetMs), 0),
    totalTokens: events.length * 150,
    estimatedCostUsd: events.length * 0.0015,
    events,
  });

  writeFileSync(resolvedPath, html, "utf-8");
  return resolvedPath;
}
